Added 'refList' as a list containing all referrals returned from server.
python-ldap/python-ldap pull request #459
Opened 2022-01-31 18:21 UTC by nickfolino

Added a refList that contains all referrals returned from the server.
Still maintains the first referral in 'info'.

2022-02-01 11:24 UTC, tiran requested changes, later dismissed
Every Python API call requires an explicit error check.

Please also include documentation update and test cases.

2022-02-01 11:24 UTC, tiran commented on Modules/constants.c
> +            PyObject *referralList = PyList_New(0);
Missing error check.

2022-02-01 11:24 UTC, tiran commented on Modules/constants.c
> +                PyObject *referralURL = Py_BuildValue("s", refs[i++]);
Use ``PyUnicode_FromString()`` and check for error (NULL).

2022-02-01 11:24 UTC, tiran commented on Modules/constants.c
> +                PyList_Append(referralList, referralURL);
Missing error check.

2022-02-01 11:24 UTC, tiran commented on Modules/constants.c
> +            PyDict_SetItemString(info, "reflist", referralList);
Missing error check

2026-09-13 19:37 UTC, droideck approved these changes
LGTM!

2026-09-23 14:10 UTC, merged