Fix(LDAPObject): ldapsearch attrlist memory error
python-ldap/python-ldap pull request #555
Opened 2024-01-07 10:01 UTC by jkoeniger

## Problem

Providing a dictionary to `attrlist` ([LDAPObject.search_ext](https://www.python-ldap.org/en/python-ldap-3.4.3/reference/ldap.html#ldap.LDAPObject.search_ext)) results in a memory error.
See Issue ()

## Root cause:

Function `PySequence_Length` can return -1 on iterables like `dict`.
The following PyMem_NEW still succeeds due `PyMem_NEW(char *, -1 + 1)`
being equivalent to `char** PyMem_Malloc(1)`, which then can result in a
segmentation fault later on.
    
## Solution

The expected behavior should be either a raised `TypeError` or that any iterable which contains only strings can be passed.
Commit e18c567 enables the latter which is in itself very unlikely to break anything. I would actually prefer to raise a `TypeError` in the C extension on encountering a dictionary as it is most likely an error on the callers side, maybe we can add that later.

The fix in e18c567 is to use `seq` and `PySequence_Fast_GET_SIZE` to determine the size of the sequence. This way any iterable which contains only strings can be used. I added two tests in a1bdf47 which will fail without the fix in e18c567.

2024-01-09 13:02 UTC, tiran requested changes
Excellent finding. Thanks for the bug report and patch with tests. Much appreciated.

I suggest a slightly different fix to align the change with other upcoming changes.

2024-01-10 10:38 UTC, jkoeniger commented on Modules/LDAPObject.c
> +	len = PySequence_Fast_GET_SIZE(seq);
Sounds good to me.

One question: If `seq` is not `NULL` shouldn't it be guaranteed that `PySequence_Size(seq);` succeeds?

2024-01-17 23:51 UTC, droideck commented on Modules/LDAPObject.c
> +	len = PySequence_Fast_GET_SIZE(seq);
@tiran may fix me, but `PySequence_Size` by specs will return -1 on failure, so it's a natural way of defensive programming to handle the call.
Yes, `seq` is not NULL, which means we are sure it's a sequence, but we can't be sure it is the correct one.

2024-01-17 23:51 UTC, droideck approved these changes, later dismissed
LGTM!

2024-01-30 09:46 UTC, jkoeniger commented
Sorry, lost track of this for a bit. I squashed the commits and adjusted the commit message.

2025-08-06 16:32 UTC, droideck commented
@jkoeniger I think it should be good to merge. Could you please rebase it?

2025-08-07 08:43 UTC, spaceone commented
@droideck @jkoeniger is in vacation for the next two weeks.

2025-08-07 08:44 UTC, spaceone commented
@tiran needs to unset the `requested changes` flag.

2025-09-01 06:35 UTC, spaceone commented
@droideck Rebase done. Can be merged.

2026-05-06 16:13 UTC, spaceone commented
Ping. This can be merged. It's also some kind of security issue as it allows DoS if you are able to control the input type!

2026-05-06 16:25 UTC, mistotebe commented
> Ping. This can be merged. It's also some kind of security issue as it allows DoS if you are able to control the input type!

Yes, the change @tiran requested seems to have been applied, I will merge tomorrow.

2026-05-07 10:37 UTC, mistotebe commented
Closed via f3f792e70d0d231efafb459d346e9f8e4bc1ca65

2026-05-07 10:37 UTC, closed without merging